domain_path: C:\Users\sidal\Documents\Code\BPSK-FPGA\vitis\bpsk_system\export\bpsk_system\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
